/**
 * The auctioneer's voice, via the browser's built-in speech synthesis.
 *
 * No audio files and no API: every call is generated by the Web Speech API
 * the browser already ships. That is what makes a real auction feel real --
 * hearing "two point five crore... three crore, Rajasthan Royals... going
 * once" is the difference between watching numbers change and being in the
 * room.
 *
 * Speech is QUEUED and interruptible. A bidding war fires faster than
 * anyone can speak, so each new line cancels the one before it rather than
 * letting the voice fall minutes behind the auction -- except for the
 * calls that matter (the lot announcement and the hammer), which are
 * allowed to finish.
 */

let enabled = true;
let voice: SpeechSynthesisVoice | null = null;
let voicesLoaded = false;

/**
 * Real neural speech (Piper) served by the backend, with the browser's
 * speechSynthesis as fallback.
 *
 * The backend does NOT synthesise per request -- every fragment is
 * pre-generated and a line is assembled by concatenating PCM (see
 * backend/game/tts.py), because synthesising on demand measured ~2.9s and a
 * bidding war fires every few hundred milliseconds.
 *
 * `usePiper` flips itself off the first time the endpoint fails, so a
 * machine without the model quietly uses the browser voice instead of
 * playing nothing at all.
 */
const TTS_BASE = (import.meta.env.VITE_BACKEND_WS_URL ?? 'ws://localhost:8000/ws/auction')
  .replace(/^ws/, 'http')
  .replace(/\/ws\/auction$/, '');

let usePiper = true;
let current: HTMLAudioElement | null = null;

function fragmentUrl(fragments: string[]): string {
  const q = fragments.map(f => `f=${encodeURIComponent(f)}`).join('&');
  return `${TTS_BASE}/tts?${q}`;
}

/** Play a line built from pre-generated fragments. Returns false if Piper
 *  is unavailable, so the caller can fall back to the browser voice. */
function playFragments(fragments: string[], interrupt: boolean): boolean {
  if (!usePiper || !enabled || fragments.length === 0) return false;
  if (interrupt) {
    // Cancel the browser voice too -- an earlier line may still be mid-
    // sentence from before Piper took over, and two voices at once is
    // worse than either one alone.
    synth()?.cancel();
    if (current) {
      current.pause();
      current = null;
    }
  }
  const audio = new Audio(fragmentUrl(fragments));
  audio.onerror = () => {
    // One failure is enough: the model is missing or the backend is old.
    usePiper = false;
    current = null;
  };
  audio.onended = () => { if (current === audio) current = null; };
  current = audio;
  void audio.play().catch(() => { usePiper = false; });
  return true;
}

/** Crore amounts, split the way the fragment cache stores them. */
function moneyFragments(cr: number): string[] {
  const whole = Math.floor(cr);
  const frac = Math.round((cr - whole) * 100);
  if (frac === 0) return [String(whole), 'crore'];
  return [`${whole} point ${frac % 10 === 0 ? frac / 10 : frac}`, 'crore'];
}

function synth(): SpeechSynthesis | null {
  if (typeof window === 'undefined' || !('speechSynthesis' in window)) return null;
  return window.speechSynthesis;
}

/** Prefer an Indian English voice, then any English one. */
function pickVoice() {
  const s = synth();
  if (!s) return;
  const all = s.getVoices();
  if (all.length === 0) return;
  voice =
    all.find(v => /en[-_]IN/i.test(v.lang)) ??
    all.find(v => /en[-_]GB/i.test(v.lang)) ??
    all.find(v => /^en/i.test(v.lang)) ??
    all[0];
  voicesLoaded = true;
}

export function initVoice() {
  const s = synth();
  if (!s) return;
  pickVoice();
  // Chrome loads voices asynchronously and fires this once they arrive.
  if (!voicesLoaded) s.onvoiceschanged = pickVoice;
}

export function setVoiceEnabled(on: boolean) {
  enabled = on;
  if (!on) {
    synth()?.cancel();
    current?.pause();
    current = null;
  }
}

export function isVoiceEnabled() {
  return enabled;
}

interface SpeakOptions {
  /** Let this line finish instead of being cut off by the next one. */
  hold?: boolean;
  rate?: number;
  pitch?: number;
}

export function say(text: string, { hold = false, rate = 1.08, pitch = 1 }: SpeakOptions = {}) {
  const s = synth();
  if (!s || !enabled || !text) return;
  // Bids arrive faster than speech; drop the stale line rather than queue a
  // backlog the auction has already moved past.
  if (!hold) s.cancel();
  const u = new SpeechSynthesisUtterance(text);
  if (voice) u.voice = voice;
  u.rate = rate;
  u.pitch = pitch;
  u.volume = 1;
  s.speak(u);
}

export function stopSpeaking() {
  synth()?.cancel();
}

/** Crore figures read far better spoken than "12.5" does. */
export function money(cr: number): string {
  const whole = Math.floor(cr);
  const frac = Math.round((cr - whole) * 100);
  if (frac === 0) return `${whole} crore`;
  if (frac === 50) return `${whole} point 5 crore`;
  if (frac === 25) return `${whole} point 2 5 crore`;
  if (frac === 75) return `${whole} point 7 5 crore`;
  return `${cr.toFixed(2).replace('.', ' point ')} crore`;
}

/** "Set M1. Lot 3. Virat Kohli. Batter, India. Base price 2 crore." */
export function announceLot(opts: {
  setName: string | null;
  lotNumber: number;
  name: string;
  role: string;
  country: string;
  basePrice: number;
}) {
  // Every player's name, role and country is in the fragment cache, so the
  // lot announcement is the same neural voice as the bidding. The lot
  // NUMBER is deliberately left out of the spoken line -- it would mean
  // caching 620 more clips to say something already on screen.
  if (playFragments(
    [opts.name, opts.role, opts.country || 'India', 'base price', ...moneyFragments(opts.basePrice)],
    true,
  )) return;

  const parts = [];
  if (opts.setName) parts.push(`Set ${opts.setName}.`);
  parts.push(`Lot ${opts.lotNumber}.`);
  parts.push(`${opts.name}.`);
  parts.push(`${opts.role}, ${opts.country}.`);
  parts.push(`Base price ${money(opts.basePrice)}.`);
  say(parts.join(' '), { hold: true, rate: 1.0 });
}

/** "3 crore, Rajasthan Royals." */
export function announceBid(amount: number, teamName: string) {
  if (playFragments([...moneyFragments(amount), teamName], true)) return;
  say(`${money(amount)}, ${teamName}.`, { rate: 1.15 });
}

/** The hammer count: 1 = going once, 2 = going twice, 3 = going thrice. */
export function announceGoing(stage: number) {
  const phrase = stage >= 3 ? 'going thrice' : stage === 2 ? 'going twice' : 'going once';
  if (playFragments([phrase], true)) return;
  const spoken = phrase.charAt(0).toUpperCase() + phrase.slice(1);
  say(`${spoken}.`, { rate: 0.95 });
}

/** "Sold! Virat Kohli to Chennai Super Kings, for 12 crore." */
export function announceSold(name: string, teamName: string, price: number) {
  // "sold! <name> to <team>, <amount> crore" -- all cached fragments.
  if (playFragments(['sold', name, 'to', teamName, ...moneyFragments(price)], true)) return;
  say(`Sold! ${name} to ${teamName}, for ${money(price)}.`, { hold: true, rate: 1.0 });
}

export function announceUnsold(name: string) {
  if (playFragments([name, 'unsold'], true)) return;
  say(`${name}, unsold.`, { hold: true, rate: 1.0 });
}
